---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

setwd("~/Coursera/Reproducible_Research/Week1/RepData_PeerAssessment1")
## Loading and preprocessing the data
activity <- read.csv("activity.csv")
#str(activity)
#names(activity)
#head(activity)
#summary(activity)

#create a vector conatining only the days that steps were recorded called complete cases.
bad <- is.na(activity[ ,1])
complete.cases <- activity[!bad, ]

## What is mean total number of steps taken per day?
#Calculate the total number of steps taken per day:
meanSteps <- tapply(complete.cases$steps, complete.cases$date, mean)
sumSteps <- tapply(complete.cases$steps, complete.cases$date, sum)
medianSteps <- tapply(complete.cases$steps, complete.cases$date, median)
#Ignore the missing values in the mean,sum and median datasets and replace them with 0:
meanSteps[is.na(meanSteps)]<-0
sumSteps[is.na(sumSteps)]<-0
medianSteps[is.na(medianSteps)]<-0
#Make a histogram of the total number of steps taken each day
hist(sumSteps,xlab="Total number of steps taken each day",main="Histogram of the total number of steps taken each day")
#Calculate and report the mean and median of the total number of steps taken per day
smean <- mean(sumSteps)
smedian <- median(sumSteps)
paste("The mean of the total number of steps taken per day is", as.character(smean))
paste("The median of the total number of steps taken per day is", as.character(smedian))
## What is the average daily activity pattern?
plot(meanSteps, type = "l", ,xlab="interval", ylab="Mean number of steps",  main="Mean number of steps")


## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
